PlanVat/Controllers/ContractorsController.cs
using PlanVat.Domain.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlanVat.Infrastructure;
using PlanVat.Models;

namespace PlanVat.Controllers
{
    public class ContractorsController : LoggingController
    {
        // GET: Contractors
        public ActionResult Index()
        {
            using (var context = new VatplanEntities())
            {
                var contractors = from c in context.Contractors
                                  select c;
                return View(contractors.ToList());
            }
        }

        // GET: Contractors/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contractors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contractors/Create
        [HttpPost]
        public ActionResult Create(ContractorViewModel contractor)
        {
            if (contractor == null)
            {
                throw new ArgumentNullException(nameof(contractor));
            }

            Log.Debug("Test debug message");

            using (var context = new VatplanEntities())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        // TODO: Add insert logic here
                        context.Contractors.Add(contractor.ToDTO());
                        context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    Log.Debug("Saving model error", ex);
                }
                return View();
            }

        }

        // GET: Contractors/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contractors/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contractors/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contractors/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PlanVat/Controllers/InvoicesController.cs
using PlanVat.Domain.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace PlanVat.Controllers
{
    public class InvoicesController : Controller
    {
        // GET: Invoices
        public ActionResult Index()
        {
            using (var context = new VatplanEntities())
            {
                var invoices = from i in context.Invoices
                               .Include("InvoiceItems")
                               .Include("InvoiceItems.ProductsInInvoices")
                               .Include("InvoiceItems.ProductsInInvoices.VatRates")
                               .Include("InvoiceItems.ProductsInInvoices.UnitsOfMeasure")
                               select i;
                return View(invoices.ToList());
            }
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            using (var context = new VatplanEntities())
            {
                ViewData["ContractorId"] = new SelectList(context.Contractors.ToList(), "Id", "Name");
                ViewData["NewProductName"] = new SelectList(context.Products.ToList(), "Id", "Name");
                var invoice = new Invoices();
                return View(invoice);
            }
        }

        // POST: Invoices/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Invoices/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Invoices/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PlanVat/Controllers/ProductsController.cs
using PlanVat.Domain.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace PlanVat.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products/Create
        public ActionResult Create()
        {
            using (var context = new VatplanEntities())
            {
                PrepareProductSelectDatas(context);
            }
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        public ActionResult Create(Products product)
        {
            using (var context = new VatplanEntities())
            {
                try
                {
                    // TODO: Add insert logic here
                    context.Products.Add(product);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    PrepareProductSelectDatas(context);
                    return View();
                }
            }
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int id)
        {
            using(var context = new VatplanEntities())
            {
                var product = context.Products.Find(id);
                context.Products.Remove(product);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // POST: Products/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int id)
        {
            using(var context = new VatplanEntities())
            {
                PrepareProductSelectDatas(context);
                return View(context.Products.Find(id));
            }
        }

        // POST: Products/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Products product)
        {
            using (var context = new VatplanEntities())
            {
                try
                {
                    context.Entry(product).State = EntityState.Modified;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch(Exception e)
                {
                    PrepareProductSelectDatas(context);
                    return View();
                }
            }
        }

        // GET: Products
        public ActionResult Index()
        {
            return GetIndexView();
        }

        private void PrepareProductSelectDatas(VatplanEntities context)
        {
            ViewData["UnitsId"] = new SelectList(context.UnitsOfMeasure.ToList(), "Id", "Name");
            ViewData["VatRateId"] = new SelectList(context.VatRates.ToList(), "Id", "Name");
        }

        private ActionResult GetIndexView()
        {
            using (var context = new VatplanEntities())
            {
                var products = from p in context.Products
                               .Include(p => p.UnitsOfMeasure)
                               .Include(p => p.VatRates)
                               select p;

                return View("Index", products.ToList());
            }
        }
    }
}

PlanVat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aplikacja do fakturowania</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VatPlan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Faktury<span class="caret">
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista", "Index", "Invoices")</li>
                            <li>@Html.ActionLink("Dodaj", "Create", "Invoices")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Kontrachenci<span class="caret">
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista", "Index", "Contractors")</li>
                            <li>@Html.ActionLink("Dodaj", "Create", "Contractors")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Produkty<span class="caret">
                            </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista", "Index", "Products")</li>
                            <li>@Html.ActionLink("Dodaj", "Create", "Products")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>